//! The BCH outer code (EN 302 307-1 §5.3.1).
//!
//! A t-error-correcting binary BCH code, shortened, over GF(2^16) for normal
//! FECFRAMEs and GF(2^14) for short ones. The generator is the product of the
//! minimal polynomials of α, α³, …, α^(2t−1) — Tables 6a/6b list them as
//! g1 … g12 — so it is built here from the field rather than typed in, and the
//! tests check its degree and its first factor against the tables.
//!
//! Bit order: the codeword is sent highest-degree coefficient first —
//! `m_(k−1) … m_0` then the parity `d_(n−k−1) … d_0` — and is held here as
//! bytes, MSB first. Every S2 code length is a whole number of bytes.
//!
//! Decoding: a byte-wise remainder (CRC-style) says in one pass whether the
//! codeword is clean, which after LDPC it nearly always is. Only otherwise are
//! syndromes, Berlekamp–Massey and a Chien search run.

use std::sync::OnceLock;

use decdvb_core::FecFrame;

/// GF(2^m) by log/antilog tables.
pub struct Gf {
    m: u32,
    /// Multiplicative order, 2^m − 1.
    n: usize,
    /// α^i for i in 0..2n (doubled so a product of two logs needs no mod).
    exp: Vec<u16>,
    /// log_α(a) for a ≠ 0.
    log: Vec<u16>,
}

impl Gf {
    /// The field generated by the primitive polynomial `poly` (bit i is the
    /// coefficient of x^i, including x^m).
    fn new(m: u32, poly: u32) -> Self {
        let n = (1usize << m) - 1;
        let mut exp = vec![0u16; 2 * n];
        let mut log = vec![0u16; n + 1];
        let mut a = 1u32;
        for (i, e) in exp.iter_mut().take(n).enumerate() {
            *e = a as u16;
            log[a as usize] = i as u16;
            a <<= 1;
            if a & (1 << m) != 0 {
                a ^= poly;
            }
        }
        assert_eq!(a, 1, "polynomial is not primitive");
        for i in n..2 * n {
            exp[i] = exp[i - n];
        }
        Gf { m, n, exp, log }
    }

    /// GF(2^16), g1(x) = 1 + x² + x³ + x⁵ + x¹⁶ (Table 6a).
    pub fn normal() -> &'static Gf {
        static F: OnceLock<Gf> = OnceLock::new();
        F.get_or_init(|| Gf::new(16, 0x1_002D))
    }

    /// GF(2^14), g1(x) = 1 + x + x³ + x⁵ + x¹⁴ (Table 6b).
    pub fn short() -> &'static Gf {
        static F: OnceLock<Gf> = OnceLock::new();
        F.get_or_init(|| Gf::new(14, 0x402B))
    }

    #[inline]
    fn mul(&self, a: u16, b: u16) -> u16 {
        if a == 0 || b == 0 {
            0
        } else {
            self.exp[self.log[a as usize] as usize + self.log[b as usize] as usize]
        }
    }

    #[inline]
    fn div(&self, a: u16, b: u16) -> u16 {
        debug_assert!(b != 0);
        if a == 0 {
            0
        } else {
            let (la, lb) = (self.log[a as usize] as usize, self.log[b as usize] as usize);
            self.exp[la + self.n - lb]
        }
    }

    /// α^i for any i ≥ 0.
    #[inline]
    fn alpha(&self, i: usize) -> u16 {
        self.exp[i % self.n]
    }

    /// The minimal polynomial of α^j over GF(2), as bits (bit i = x^i).
    fn minimal_polynomial(&self, j: usize) -> Vec<bool> {
        // The conjugates α^(j·2^k) are its roots.
        let mut roots = Vec::new();
        let mut e = j % self.n;
        loop {
            roots.push(e);
            e = (e * 2) % self.n;
            if e == j % self.n {
                break;
            }
        }
        // Multiply out Π (x + α^e) in GF(2^m); the coefficients land in GF(2).
        let mut poly = vec![1u16];
        for &r in &roots {
            let root = self.alpha(r);
            let mut next = vec![0u16; poly.len() + 1];
            for (i, &c) in poly.iter().enumerate() {
                next[i + 1] ^= c;
                next[i] ^= self.mul(c, root);
            }
            poly = next;
        }
        poly.iter()
            .map(|&c| {
                assert!(c <= 1, "minimal polynomial not binary");
                c == 1
            })
            .collect()
    }
}

/// A 192-bit register, left-aligned: bit 191 is the highest coefficient.
type Reg = [u64; 3];

#[inline]
fn shl8(r: &mut Reg) {
    r[0] = (r[0] << 8) | (r[1] >> 56);
    r[1] = (r[1] << 8) | (r[2] >> 56);
    r[2] <<= 8;
}

#[inline]
fn xor(r: &mut Reg, t: &Reg) {
    r[0] ^= t[0];
    r[1] ^= t[1];
    r[2] ^= t[2];
}

/// Bit `i` of a left-aligned register counted from the top (0 = bit 191).
#[inline]
fn bit_from_top(r: &Reg, i: usize) -> bool {
    (r[i / 64] >> (63 - i % 64)) & 1 == 1
}

/// Why a BCH decode failed.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum BchError {
    #[error("more errors than the code can correct")]
    Uncorrectable,
}

/// One BCH code: a field, a correction power and a codeword length.
pub struct Bch {
    gf: &'static Gf,
    t: usize,
    /// Codeword length in bits (shortened).
    n_bits: usize,
    /// Parity bits, m·t.
    p: usize,
    /// Byte-wise remainder table, left-aligned.
    table: Box<[Reg; 256]>,
}

impl Bch {
    /// The code for a frame length, correction power and BCH codeword length
    /// (N_bch of Table 5a/5b).
    pub fn new(frame: FecFrame, t: usize, n_bits: usize) -> Self {
        let gf = match frame {
            FecFrame::Normal => Gf::normal(),
            FecFrame::Short => Gf::short(),
            FecFrame::Medium => unimplemented!("medium FECFRAMEs are S2X (M3)"),
        };
        let g = generator(gf, t);
        let p = g.len() - 1;
        assert_eq!(p, gf.m as usize * t, "generator degree");
        assert!(p.is_multiple_of(8) && n_bits.is_multiple_of(8) && p <= 192);

        // g without its x^p term, left-aligned: x^(p-1) at bit 191.
        let mut g_low: Reg = [0; 3];
        for i in 0..p {
            if g[p - 1 - i] {
                g_low[i / 64] |= 1 << (63 - i % 64);
            }
        }
        // table[v] = v(x)·x^p mod g(x): run the 8 bits of v through the LFSR.
        let mut table = Box::new([[0u64; 3]; 256]);
        for (v, entry) in table.iter_mut().enumerate() {
            let mut r: Reg = [0; 3];
            for b in (0..8).rev() {
                let fb = ((v >> b) & 1 == 1) ^ bit_from_top(&r, 0);
                // Shift left one bit across the limbs.
                r[0] = (r[0] << 1) | (r[1] >> 63);
                r[1] = (r[1] << 1) | (r[2] >> 63);
                r[2] <<= 1;
                if fb {
                    xor(&mut r, &g_low);
                }
            }
            *entry = r;
        }
        Bch {
            gf,
            t,
            n_bits,
            p,
            table,
        }
    }

    /// Parity bytes.
    pub fn parity_bytes(&self) -> usize {
        self.p / 8
    }

    /// Message bytes (K_bch / 8).
    pub fn message_bytes(&self) -> usize {
        (self.n_bits - self.p) / 8
    }

    /// x^p · bytes(x) mod g(x), left-aligned.
    fn remainder(&self, bytes: &[u8]) -> Reg {
        let mut r: Reg = [0; 3];
        for &b in bytes {
            let top = ((r[0] >> 56) as u8 ^ b) as usize;
            shl8(&mut r);
            xor(&mut r, &self.table[top]);
        }
        r
    }

    /// Fill the parity bytes at the end of `codeword` from the message before
    /// them (systematic encoding).
    pub fn encode(&self, codeword: &mut [u8]) {
        let k = self.message_bytes();
        assert_eq!(codeword.len(), k + self.parity_bytes());
        let r = self.remainder(&codeword[..k]);
        for (i, out) in codeword[k..].iter_mut().enumerate() {
            *out = (r[i / 8] >> (56 - 8 * (i % 8))) as u8;
        }
    }

    /// Correct `codeword` in place; returns how many bits were flipped.
    pub fn decode(&self, codeword: &mut [u8]) -> Result<usize, BchError> {
        assert_eq!(codeword.len() * 8, self.n_bits);
        let r = self.remainder(codeword);
        if r == [0; 3] {
            return Ok(0);
        }
        let gf = self.gf;

        // Syndromes S_j = c(α^j), j = 1..2t. The remainder R(x) holds
        // x^p·c(x) mod g(x), so c(α^j) = R(α^j)·α^(−jp) for the roots of g.
        let mut s = vec![0u16; 2 * self.t + 1];
        for j in (1..=2 * self.t).step_by(2) {
            let mut acc = 0u16;
            for i in 0..self.p {
                if bit_from_top(&r, i) {
                    // Bit i from the top is the coefficient of x^(p−1−i).
                    acc ^= gf.alpha(j * (self.p - 1 - i));
                }
            }
            let shift = (gf.n - (j * self.p) % gf.n) % gf.n;
            s[j] = gf.mul(acc, gf.alpha(shift));
        }
        // Binary code: S_2j = S_j².
        for j in 1..=self.t {
            s[2 * j] = gf.mul(s[j], s[j]);
        }

        // Berlekamp–Massey: the error locator Λ(x) = Π (1 + X_l·x).
        let mut c = vec![0u16; 2 * self.t + 2];
        let mut b = vec![0u16; 2 * self.t + 2];
        c[0] = 1;
        b[0] = 1;
        let (mut l, mut m, mut bd) = (0usize, 1usize, 1u16);
        for k in 0..2 * self.t {
            let mut d = s[k + 1];
            for i in 1..=l {
                d ^= gf.mul(c[i], s[k + 1 - i]);
            }
            if d == 0 {
                m += 1;
                continue;
            }
            let coef = gf.div(d, bd);
            let prev = c.clone();
            for i in 0..c.len() - m {
                c[i + m] ^= gf.mul(coef, b[i]);
            }
            if 2 * l <= k {
                l = k + 1 - l;
                b = prev;
                bd = d;
                m = 1;
            } else {
                m += 1;
            }
        }
        if l > self.t {
            return Err(BchError::Uncorrectable);
        }

        // Chien search over the shortened positions: an error at degree e
        // makes Λ(α^(−e)) = 0. Track each term λ_i·α^(−i·e) by its log.
        let n = gf.n;
        let mut logs: Vec<Option<usize>> = (1..=l)
            .map(|i| (c[i] != 0).then(|| gf.log[c[i] as usize] as usize))
            .collect();
        let mut found = Vec::with_capacity(l);
        for e in 0..self.n_bits {
            let mut sum = 1u16; // λ_0
            for (i, lg) in logs.iter_mut().enumerate() {
                if let Some(v) = lg {
                    sum ^= gf.exp[*v];
                    // Next position: multiply by α^(−(i+1)).
                    *v = (*v + n - (i + 1)) % n;
                }
            }
            if sum == 0 {
                found.push(e);
                if found.len() == l {
                    break;
                }
            }
        }
        if found.len() != l {
            return Err(BchError::Uncorrectable);
        }
        for e in found {
            // Degree e is bit n−1−e of the stream.
            let bit = self.n_bits - 1 - e;
            codeword[bit / 8] ^= 0x80 >> (bit % 8);
        }
        Ok(l)
    }
}

/// g(x) = Π minimal polynomials of α^(2i−1), i = 1..t, as bits (bit i = x^i).
fn generator(gf: &Gf, t: usize) -> Vec<bool> {
    let mut g = vec![true];
    for i in 1..=t {
        let mp = gf.minimal_polynomial(2 * i - 1);
        let mut out = vec![false; g.len() + mp.len() - 1];
        for (a, &ga) in g.iter().enumerate() {
            if ga {
                for (b, &mb) in mp.iter().enumerate() {
                    out[a + b] ^= mb;
                }
            }
        }
        g = out;
    }
    g
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::params::all_s2;

    fn rng(seed: u64) -> impl FnMut() -> u64 {
        let mut s = seed | 1;
        move || {
            s ^= s >> 12;
            s ^= s << 25;
            s ^= s >> 27;
            s.wrapping_mul(0x2545_F491_4F6C_DD1D)
        }
    }

    #[test]
    fn first_factors_are_the_tables_g1() {
        // g1 is the field polynomial itself (Tables 6a/6b).
        let g1 = Gf::normal().minimal_polynomial(1);
        let want: Vec<usize> = vec![0, 2, 3, 5, 16];
        let got: Vec<usize> = (0..g1.len()).filter(|&i| g1[i]).collect();
        assert_eq!(got, want);
        let g1 = Gf::short().minimal_polynomial(1);
        let got: Vec<usize> = (0..g1.len()).filter(|&i| g1[i]).collect();
        assert_eq!(got, vec![0, 1, 3, 5, 14]);
        // Every factor has full degree, so the parity is m·t bits.
        for j in (1..24).step_by(2) {
            assert_eq!(Gf::normal().minimal_polynomial(j).len(), 17, "α^{j}");
            assert_eq!(Gf::short().minimal_polynomial(j).len(), 15, "α^{j}");
        }
    }

    #[test]
    fn corrects_up_to_t_errors_in_every_code() {
        let mut next = rng(5);
        for p in all_s2() {
            let bch = Bch::new(p.frame, p.t, p.n_bch);
            let mut cw: Vec<u8> = (0..p.n_bch / 8).map(|_| next() as u8).collect();
            bch.encode(&mut cw);
            let clean = cw.clone();
            assert_eq!(bch.decode(&mut cw.clone()), Ok(0), "{p:?}");

            for errors in [1, p.t / 2, p.t] {
                let mut bad = clean.clone();
                let mut flipped = std::collections::BTreeSet::new();
                while flipped.len() < errors {
                    flipped.insert((next() % p.n_bch as u64) as usize);
                }
                for &b in &flipped {
                    bad[b / 8] ^= 0x80 >> (b % 8);
                }
                assert_eq!(bch.decode(&mut bad), Ok(errors), "{p:?} with {errors}");
                assert_eq!(bad, clean, "{p:?} with {errors}");
            }
        }
    }

    #[test]
    fn reports_too_many_errors() {
        let mut next = rng(6);
        let p = all_s2().next().unwrap();
        let bch = Bch::new(p.frame, p.t, p.n_bch);
        let mut cw: Vec<u8> = (0..p.n_bch / 8).map(|_| next() as u8).collect();
        bch.encode(&mut cw);
        let mut failures = 0;
        for _ in 0..20 {
            let mut bad = cw.clone();
            for _ in 0..p.t + 6 {
                let b = (next() % p.n_bch as u64) as usize;
                bad[b / 8] ^= 0x80 >> (b % 8);
            }
            if bch.decode(&mut bad).is_err() {
                failures += 1;
            }
        }
        // Beyond t a BCH decoder may miscorrect, but rarely for a shortened
        // code this long.
        assert!(failures >= 19, "only {failures} of 20 flagged");
    }
}
